title: OE5XRX
description: Amateurfunkclub für Remote Stationen

theme: just-the-docs
favicon_ico: /favicon.ico
logo: "/Amateurfunkclub_Logo_compressed.jpg"

mermaid:
  version: "11.3.0"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

gems:
- jekyll-email-protect
