title: OE5XRX
description: Amateurfunkclub für Remote Stationen

gems: [jekyll-mermaid]

theme: just-the-docs

mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@11.3.0/dist/mermaid.min.js'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
