title: OE5XRX
description: Amateurfunkclub für Remote Stationen

gems: [jekyll-mermaid]

plugins:
  - jekyll-remote-theme

mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@11.3.0/dist/mermaid.min.js'

remote_theme: benbalter/retlab